require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/brewers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Brewer. As you add validations to Brewer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Brewer.create! valid_attributes
      get brewers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      brewer = Brewer.create! valid_attributes
      get brewer_url(brewer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_brewer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      brewer = Brewer.create! valid_attributes
      get edit_brewer_url(brewer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Brewer" do
        expect {
          post brewers_url, params: { brewer: valid_attributes }
        }.to change(Brewer, :count).by(1)
      end

      it "redirects to the created brewer" do
        post brewers_url, params: { brewer: valid_attributes }
        expect(response).to redirect_to(brewer_url(Brewer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Brewer" do
        expect {
          post brewers_url, params: { brewer: invalid_attributes }
        }.to change(Brewer, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post brewers_url, params: { brewer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested brewer" do
        brewer = Brewer.create! valid_attributes
        patch brewer_url(brewer), params: { brewer: new_attributes }
        brewer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the brewer" do
        brewer = Brewer.create! valid_attributes
        patch brewer_url(brewer), params: { brewer: new_attributes }
        brewer.reload
        expect(response).to redirect_to(brewer_url(brewer))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        brewer = Brewer.create! valid_attributes
        patch brewer_url(brewer), params: { brewer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested brewer" do
      brewer = Brewer.create! valid_attributes
      expect {
        delete brewer_url(brewer)
      }.to change(Brewer, :count).by(-1)
    end

    it "redirects to the brewers list" do
      brewer = Brewer.create! valid_attributes
      delete brewer_url(brewer)
      expect(response).to redirect_to(brewers_url)
    end
  end
end
